In [ ]:
thresholds = np.linspace(1e-7, 1e-5, 100)
topks = [4, 6, 12, 16, 24, 32]

In [ ]:
ablated_metrics, n_nodes_counts = circuitizer.run_ablated_metrics(thresholds, topks)

In [ ]:
target_metric = (max(ablated_metrics) - min(ablated_metrics)) * 0.95 + min(ablated_metrics)
target_threshold = [threshold for threshold, metric in reversed(list(zip(thresholds, ablated_metrics))) if metric > target_metric][0]

  0%|          | 0/320 [00:00<?, ?it/s]

  0%|          | 0/90 [00:00<?, ?it/s, ('arrow', 'a', 16)]

  0%|          | 0/19 [00:00<?, ?it/s, ('input', 'a', 16)]

  0%|          | 0/16 [00:00<?, ?it/s, ('newline', 'a', 16)]

  0%|          | 0/64 [00:00<?, ?it/s, ('output', 'a', 16)]

  0%|          | 0/7 [00:00<?, ?it/s, ('prompt', 'a', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'ea', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'ea', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'ea', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'ea', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'ea', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'er', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'er', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'er', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'er', 16)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'er', 16)]

  0%|          | 0/33 [00:00<?, ?it/s, ('arrow', 'r', 16)]

  0%|          | 0/17 [00:00<?, ?it/s, ('input', 'r', 16)]

  0%|          | 0/7 [00:00<?, ?it/s, ('newline', 'r', 16)]

  0%|          | 0/16 [00:00<?, ?it/s, ('output', 'r', 16)]

  0%|          | 0/5 [00:00<?, ?it/s, ('prompt', 'r', 16)]

  0%|          | 0/100 [00:00<?, ?it/s, ('arrow', 'a', 15)]

  0%|          | 0/26 [00:00<?, ?it/s, ('input', 'a', 15)]

  0%|          | 0/21 [00:00<?, ?it/s, ('newline', 'a', 15)]

  0%|          | 0/32 [00:00<?, ?it/s, ('output', 'a', 15)]

  0%|          | 0/26 [00:00<?, ?it/s, ('prompt', 'a', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'ea', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'ea', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'ea', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'ea', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'ea', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'er', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'er', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'er', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'er', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'er', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'et', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'et', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'et', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'et', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'et', 15)]

  0%|          | 0/35 [00:00<?, ?it/s, ('arrow', 'r', 15)]

  0%|          | 0/34 [00:00<?, ?it/s, ('input', 'r', 15)]

  0%|          | 0/7 [00:00<?, ?it/s, ('newline', 'r', 15)]

  0%|          | 0/24 [00:00<?, ?it/s, ('output', 'r', 15)]

  0%|          | 0/8 [00:00<?, ?it/s, ('prompt', 'r', 15)]

  0%|          | 0/12 [00:00<?, ?it/s, ('arrow', 't', 15)]

  0%|          | 0/2 [00:00<?, ?it/s, ('input', 't', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 't', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 't', 15)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 't', 15)]

  0%|          | 0/57 [00:00<?, ?it/s, ('arrow', 'a', 14)]

  0%|          | 0/55 [00:00<?, ?it/s, ('input', 'a', 14)]

  0%|          | 0/15 [00:00<?, ?it/s, ('newline', 'a', 14)]

  0%|          | 0/54 [00:00<?, ?it/s, ('output', 'a', 14)]

  0%|          | 0/9 [00:00<?, ?it/s, ('prompt', 'a', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'ea', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'ea', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'ea', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'ea', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'ea', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'er', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'er', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'er', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'er', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'er', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('arrow', 'et', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('input', 'et', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 'et', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 'et', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 'et', 14)]

  0%|          | 0/30 [00:00<?, ?it/s, ('arrow', 'r', 14)]

  0%|          | 0/46 [00:00<?, ?it/s, ('input', 'r', 14)]

  0%|          | 0/11 [00:00<?, ?it/s, ('newline', 'r', 14)]

  0%|          | 0/42 [00:00<?, ?it/s, ('output', 'r', 14)]

  0%|          | 0/8 [00:00<?, ?it/s, ('prompt', 'r', 14)]

  0%|          | 0/17 [00:00<?, ?it/s, ('arrow', 't', 14)]

  0%|          | 0/2 [00:00<?, ?it/s, ('input', 't', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('newline', 't', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('output', 't', 14)]

  0%|          | 0/1 [00:00<?, ?it/s, ('prompt', 't', 14)]

  0%|          | 0/120 [00:00<?, ?it/s, ('arrow', 'a', 13)]

  0%|          | 0/76 [00:00<?, ?it/s, ('input', 'a', 13)]

KeyboardInterrupt: 

In [51]:
featuress

<jax.Array(-1.248209e-05, dtype=float32)>

In [52]:
feature_effectss

{('er', 8, 'arrow'): <jax.Array(-1.248209e-05, dtype=float32)>,
 ('er', 8, 'input'): <jax.Array(-3.386186e-06, dtype=float32)>,
 ('er', 8, 'newline'): <jax.Array(1.2659609e-06, dtype=float32)>,
 ('er', 8, 'output'): <jax.Array(2.1368157e-07, dtype=float32)>,
 ('er', 8, 'prompt'): <jax.Array(6.4502055e-06, dtype=float32)>,
 ('r',
  8,
  'arrow'): # jax.Array float32(32768,) ≈-1.4e-09 ±1.3e-07 [≥-1.7e-05, ≤5.3e-06] zero:32_079 nonzero:689
   Array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
 ,
 ('r',
  8,
  'input'): # jax.Array float32(32768,) ≈6.6e-10 ±6.1e-08 [≥-3.4e-06, ≤4.6e-06] zero:29_849 nonzero:2_919
   Array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
 ,
 ('r',
  8,
  'newline'): # jax.Array float32(32768,) ≈7.8e-10 ±5.9e-08 [≥-3.4e-06, ≤6.1e-06] zero:32_103 nonzero:665
   Array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
 ,
 ('r',
  8,
  'output'): # jax.Array float32(32768,) ≈-2.4e-10 ±2.2e-08 [≥-1.7e-06, ≤1.1e-06] zero:31_402 nonzero:1_366
   Array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
 ,
 ('r',
  8,
  'prompt'): # jax.Array float32(32768,) ≈5.6e-10 ±1.5e-07 [≥-1.7e-05, ≤7.9e-06] zero:32_656 nonzero:112
   Array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
 }

In [ ]:
import os
if "models" not in os.listdir("."):
    os.chdir("../..")

In [ ]:
%load_ext autoreload
%autoreload 2
import penzai
import jax_smi
jax_smi.initialise_tracking()
from penzai import pz
pz.ts.register_as_default()
pz.ts.register_autovisualize_magic()
pz.enable_interactive_context()

In [ ]:
%env JAX_TRACEBACK_FILTERING=off
import jax
jax.config.update('jax_traceback_filtering', 'off')


In [ ]:
from sprint.icl_sfc_utils import Circuitizer

In [ ]:
from micrlhf.llama import LlamaTransformer
llama = LlamaTransformer.from_pretrained("models/gemma-2b-it.gguf", from_type="gemma", load_eager=True, device_map="tpu:0")

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("alpindale/gemma-2b")
tokenizer.padding_side = "right"

In [ ]:
from sprint.task_vector_utils import load_tasks, ICLRunner
tasks = load_tasks()

In [ ]:
def check_if_single_token(token):
    return len(tokenizer.tokenize(token)) == 1

task_name = "es_en"

task = tasks[task_name]

print(len(task))

task = {
    k:v for k,v in task.items() if check_if_single_token(k) and check_if_single_token(v)
}

print(len(task))

pairs = list(task.items())

batch_size = 8 
n_shot=20
max_seq_len = 128
seed = 10

prompt = "Follow the pattern:\n{}"

runner = ICLRunner(task_name, pairs, batch_size=batch_size, n_shot=n_shot, max_seq_len=max_seq_len, seed=seed, prompt=prompt)

In [ ]:
layers = list(range(6, 17))
circuitizer = Circuitizer(llama, tokenizer, runner, layers, prompt)

In [ ]:
thresholds = np.linspace(1e-7, 1e-5, 100)
topks = [4, 6, 12, 16, 24, 32]

In [ ]:
ablated_metrics, n_nodes_counts = circuitizer.run_ablated_metrics(thresholds)

In [ ]:
target_metric = (max(ablated_metrics) - min(ablated_metrics)) * 0.95 + min(ablated_metrics)
target_threshold = [threshold for threshold, metric in reversed(list(zip(thresholds, ablated_metrics))) if metric > target_metric][0]

In [ ]:
from tqdm.auto import tqdm
import numpy as np

combined_ies = {}
typed_ies = {
    "r": circuitizer.ie_resid,
    "a": circuitizer.ie_attn,
    "t": circuitizer.ie_transcoder,
}

for layer in tqdm(layers):
    for type in typed_ies:
        if layer in typed_ies[type]: 
            ies = typed_ies[type][layer]
            for mask in circuitizer.masks:
                ies_mask = circuitizer.mask_average(ies, mask)
                i = np.nonzero(np.abs(ies_mask) > target_threshold)[0]
                w = ies_mask[i]

                for idx, weight in zip(i.tolist(), w.tolist()):
                    combined_ies[(layer, mask, type, idx)] = weight

                # w, i = jax.lax.top_k(ies_mask, 4)
                # for idx, weight in zip(i.tolist(), w.tolist()):
                #     combined_ies[(layer, mask, type, idx)] = weight

In [ ]:
combined_ies = [
    key + (weight,)
    for key, weight in combined_ies.items()
]

In [ ]:
typed_ies_error = {
    "er": circuitizer.ie_error_resid,
    "ea": circuitizer.ie_error_attn,
    "et": circuitizer.ie_error_transcoder,
}

for layer in tqdm(layers):
    for type in typed_ies_error:
        if layer in typed_ies_error[type]: 
            ies = typed_ies_error[type][layer]
            for mask in circuitizer.masks:
                ies_mask = circuitizer.mask_average(ies, mask)
                # print(ies_mask.tolist())
                # raise
                combined_ies.append((layer, mask, type, 0, ies_mask.tolist()))

In [ ]:
combined_ies = sorted(combined_ies, key=lambda x: -x[-1])

In [ ]:
important_feats_masks = {}
for mask in circuitizer.masks:
    important_feats_masks[mask] = [
        (type, layer, feat) for layer, f_mask, type, feat, _ in combined_ies if f_mask == mask
        ]

In [ ]:
from collections import defaultdict
flat_feats = defaultdict(list)
for k, v in important_feats_masks.items():
    for type, layer, feat in v:
        flat_feats[(k, type, layer)].append(feat)

In [ ]:
from tqdm.auto import trange
import jax.numpy as jnp
graph = []

batch_size = 16
k = 32
for type, features in tqdm(sorted(flat_feats.items(), key=lambda x: (-x[0][-1], x[0][-2], x[0][-3]))):
    mask, feature_type, layer = type
    mask = jnp.array(list(circuitizer.masks.keys()).index(mask))
    for batch in trange(0, len(features), batch_size, postfix=str(type)):
        batch_features = features[batch:batch+batch_size]
        orig_length = len(batch_features)
        batch_features = batch_features + [0] * (batch_size - len(batch_features))
        feature_effectss = jax.vmap(lambda x: circuitizer.compute_feature_effects(feature_type, layer, x, mask, layer_window=1))(jnp.asarray(batch_features))
        # feature_effectss = circuitizer.compute_feature_effects(feature_type, layer, batch_features, mask, layer_window=1)
        
        top_effects = defaultdict(list)
        for key, featuress in feature_effectss.items():
            for elem, feature_effects in enumerate(featuress):
                if elem >= orig_length:
                    continue
                if feature_effects.ndim == 0:
                    top_effects[elem].append((float(feature_effects), key, 0))
                    continue
                effects, indices = jax.lax.top_k(jnp.abs(feature_effects), k)
                for i, e in zip(indices.tolist(), effects.tolist()):
                    top_effects[elem].append((e, key, i))
        for elem, effects in top_effects.items():
            effects.sort(reverse=True)
            edges = effects[:k]
            graph.extend([(weight, batch_features[elem], downstream_feature) for weight, _, downstream_feature in edges])
        
        # # edges = circuitizer.compute_edges(*feature, mask, layer_window=1)
        # graph.extend([(weight, feature, downstream_feature) for weight, _, downstream_feature in edges])
    
        # for feature in tqdm(batch_features):
        #     feature_effects = circuitizer.compute_feature_effects(feature_type, layer, feature, mask, layer_window=1)
        #     top_effects = []
        #     for key, features in feature_effects.items():
        #         if features.ndim == 0:
        #             top_effects.append((float(features), key, 0))
        #             continue
        #         effects, indices = jax.lax.top_k(jnp.abs(features), k)
        #         for i, e in zip(indices.tolist(), effects.tolist()):
        #             top_effects.append((e, key, i))
        #     top_effects.sort(reverse=True)
        #     edges = top_effects[:k]
            
        #     # edges = circuitizer.compute_edges(*feature, mask, layer_window=1)
        #     graph.extend([(weight, feature, downstream_feature) for weight, _, downstream_feature in edges])



# for mask, features in tqdm(important_feats_masks.items()):
#     for batch in trange(0, len(features), batch_size):
#         batch_features = features[batch:batch+batch_size]
        
        
#         for feature in tqdm(batch_features):
#             # edges = circuitizer.compute_edges(*feature, mask, layer_window=1)
#             graph.extend([(weight, feature, downstream_feature) for weight, _, downstream_feature in edges])


#     # for downstream_feature in tqdm(features):
#     #     edges = compute_edges(downstream_feature, mask, layer_window=1)
#     #     graph.extend([(weight, upstream_feature_key + (upstream_feature,), downstream_feature[:2] + (mask,) + downstream_feature[2:])
#     #                   for weight, upstream_feature_key, upstream_feature in edges])